### ISSUE TITLE
package not working for 100% sure

### ISSUE THREAD

**Issue by m0x61h0x64i** [hoangnguyen1247/multer-minio-storage#20]
i just went to package page on npmjs.com

copy pated the usage guide and set the minio vaiables and got this error :

```
TypeError: multerMinIOStorage is not a function
```

**Comment by hoangnguyen1247** [comment]
Hi @m0x31h0x64i 
Please check your package.json or compile tool. I don't think it's error from package

**Comment by craftycram** [comment]
i have the same issue after switching from commonjs to esm

**Comment by moussaab-moulim** [comment]
yes same problem here
